"""Initial migration

Revision ID: b837c6e261e1
Revises: 
Create Date: 2025-12-10 17:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b837c6e261e1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id_key', name=op.f('pk_categories'))
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_name'), ['name'], unique=False)

    op.create_table('clients',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('lastname', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id_key', name=op.f('pk_clients'))
    )
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clients_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_clients_lastname'), ['lastname'], unique=False)
        batch_op.create_index(batch_op.f('ix_clients_name'), ['name'], unique=False)

    op.create_table('addresses',
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id_key'], name=op.f('fk_addresses_client_id_clients')),
    sa.PrimaryKeyConstraint('id_key', name=op.f('pk_addresses'))
    )
    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_addresses_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_addresses_street'), ['street'], unique=False)

    op.create_table('bills',
    sa.Column('bill_number', sa.String(), nullable=False),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('payment_type', sa.Enum('CASH', 'CARD', 'DEBIT', 'CREDIT', 'BANK_TRANSFER', name='paymenttype'), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id_key'], name=op.f('fk_bills_client_id_clients')),
    sa.PrimaryKeyConstraint('id_key', name=op.f('pk_bills'))
    )
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bills_bill_number'), ['bill_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_bills_client_id'), ['client_id'], unique=False)

    op.create_table('products',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id_key'], name=op.f('fk_products_category_id_categories')),
    sa.PrimaryKeyConstraint('id_key', name=op.f('pk_products'))
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_name'), ['name'], unique=False)

    op.create_table('orders',
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('delivery_method', sa.Enum('DRIVE_THRU', 'ON_HAND', 'HOME_DELIVERY', name='deliverymethod'), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'DELIVERED', 'CANCELED', name='status'), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('bill_id', sa.Integer(), nullable=True),
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id_key'], name=op.f('fk_orders_bill_id_bills')),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id_key'], name=op.f('fk_orders_client_id_clients')),
    sa.PrimaryKeyConstraint('id_key', name=op.f('pk_orders'))
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_orders_bill_id'), ['bill_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_client_id'), ['client_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_delivery_method'), ['delivery_method'], unique=False)
        batch_op.create_index(batch_op.f('ix_orders_status'), ['status'], unique=False)

    op.create_table('reviews',
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('id_key', sa.Integer(), autoincrement=True, nullable=False),
    sa.CheckConstraint('rating >= 1.0 AND rating <= 5.0', name='check_rating_range'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id_key'], name=op.f('fk_reviews_product_id_products')),
    sa.PrimaryKeyConstraint('id_key', name=op.f('pk_reviews'))
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_product_id'), ['product_id'], unique=False)

    op.create_table('order_details',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id_key'], name=op.f('fk_order_details_order_id_orders')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id_key'], name=op.f('fk_order_details_product_id_products')),
    sa.PrimaryKeyConstraint('order_id', 'product_id', name=op.f('pk_order_details'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order_details')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_product_id'))
    op.drop_table('reviews')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_orders_status'))
        batch_op.drop_index(batch_op.f('ix_orders_delivery_method'))
        batch_op.drop_index(batch_op.f('ix_orders_date'))
        batch_op.drop_index(batch_op.f('ix_orders_client_id'))
        batch_op.drop_index(batch_op.f('ix_orders_bill_id'))
    op.drop_table('orders')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_name'))
        batch_op.drop_index(batch_op.f('ix_products_category_id'))
    op.drop_table('products')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bills_client_id'))
        batch_op.drop_index(batch_op.f('ix_bills_bill_number'))
    op.drop_table('bills')

    with op.batch_alter_table('addresses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_addresses_street'))
        batch_op.drop_index(batch_op.f('ix_addresses_client_id'))
    op.drop_table('addresses')
    
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clients_name'))
        batch_op.drop_index(batch_op.f('ix_clients_lastname'))
        batch_op.drop_index(batch_op.f('ix_clients_email'))
    op.drop_table('clients')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_name'))
    op.drop_table('categories')
    # ### end Alembic commands ###
